/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ZettelsRouteImport } from './routes/zettels'
import { Route as TimelineRouteImport } from './routes/timeline'
import { Route as GraphRouteImport } from './routes/graph'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ZettelsIndexRouteImport } from './routes/zettels.index'
import { Route as ZettelsZettelIdRouteImport } from './routes/zettels.$zettelId'
import { Route as EventsEventIdRouteImport } from './routes/events.$eventId'

const ZettelsRoute = ZettelsRouteImport.update({
  id: '/zettels',
  path: '/zettels',
  getParentRoute: () => rootRouteImport,
} as any)
const TimelineRoute = TimelineRouteImport.update({
  id: '/timeline',
  path: '/timeline',
  getParentRoute: () => rootRouteImport,
} as any)
const GraphRoute = GraphRouteImport.update({
  id: '/graph',
  path: '/graph',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ZettelsIndexRoute = ZettelsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ZettelsRoute,
} as any)
const ZettelsZettelIdRoute = ZettelsZettelIdRouteImport.update({
  id: '/$zettelId',
  path: '/$zettelId',
  getParentRoute: () => ZettelsRoute,
} as any)
const EventsEventIdRoute = EventsEventIdRouteImport.update({
  id: '/events/$eventId',
  path: '/events/$eventId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/graph': typeof GraphRoute
  '/timeline': typeof TimelineRoute
  '/zettels': typeof ZettelsRouteWithChildren
  '/events/$eventId': typeof EventsEventIdRoute
  '/zettels/$zettelId': typeof ZettelsZettelIdRoute
  '/zettels/': typeof ZettelsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/graph': typeof GraphRoute
  '/timeline': typeof TimelineRoute
  '/events/$eventId': typeof EventsEventIdRoute
  '/zettels/$zettelId': typeof ZettelsZettelIdRoute
  '/zettels': typeof ZettelsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/graph': typeof GraphRoute
  '/timeline': typeof TimelineRoute
  '/zettels': typeof ZettelsRouteWithChildren
  '/events/$eventId': typeof EventsEventIdRoute
  '/zettels/$zettelId': typeof ZettelsZettelIdRoute
  '/zettels/': typeof ZettelsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/graph'
    | '/timeline'
    | '/zettels'
    | '/events/$eventId'
    | '/zettels/$zettelId'
    | '/zettels/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/graph'
    | '/timeline'
    | '/events/$eventId'
    | '/zettels/$zettelId'
    | '/zettels'
  id:
    | '__root__'
    | '/'
    | '/graph'
    | '/timeline'
    | '/zettels'
    | '/events/$eventId'
    | '/zettels/$zettelId'
    | '/zettels/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GraphRoute: typeof GraphRoute
  TimelineRoute: typeof TimelineRoute
  ZettelsRoute: typeof ZettelsRouteWithChildren
  EventsEventIdRoute: typeof EventsEventIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/zettels': {
      id: '/zettels'
      path: '/zettels'
      fullPath: '/zettels'
      preLoaderRoute: typeof ZettelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/timeline': {
      id: '/timeline'
      path: '/timeline'
      fullPath: '/timeline'
      preLoaderRoute: typeof TimelineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/graph': {
      id: '/graph'
      path: '/graph'
      fullPath: '/graph'
      preLoaderRoute: typeof GraphRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/zettels/': {
      id: '/zettels/'
      path: '/'
      fullPath: '/zettels/'
      preLoaderRoute: typeof ZettelsIndexRouteImport
      parentRoute: typeof ZettelsRoute
    }
    '/zettels/$zettelId': {
      id: '/zettels/$zettelId'
      path: '/$zettelId'
      fullPath: '/zettels/$zettelId'
      preLoaderRoute: typeof ZettelsZettelIdRouteImport
      parentRoute: typeof ZettelsRoute
    }
    '/events/$eventId': {
      id: '/events/$eventId'
      path: '/events/$eventId'
      fullPath: '/events/$eventId'
      preLoaderRoute: typeof EventsEventIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ZettelsRouteChildren {
  ZettelsZettelIdRoute: typeof ZettelsZettelIdRoute
  ZettelsIndexRoute: typeof ZettelsIndexRoute
}

const ZettelsRouteChildren: ZettelsRouteChildren = {
  ZettelsZettelIdRoute: ZettelsZettelIdRoute,
  ZettelsIndexRoute: ZettelsIndexRoute,
}

const ZettelsRouteWithChildren =
  ZettelsRoute._addFileChildren(ZettelsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GraphRoute: GraphRoute,
  TimelineRoute: TimelineRoute,
  ZettelsRoute: ZettelsRouteWithChildren,
  EventsEventIdRoute: EventsEventIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
